name: note_app
description: Aplikasi catatan modern - offline first
publish_to: 'none'
version: 2.4.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Database
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4

  # Storage lokal (setting)
  shared_preferences: ^2.3.2

  # File & share
  file_picker: ^8.1.2
  share_plus: ^10.0.2

  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1

  # Security
  crypto: ^3.0.6
  local_auth: ^2.3.0

  # Google Drive backup
  google_sign_in: ^6.2.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  image_picker: ^1.1.2
  flutter_quill: ^9.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
